# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('shopId', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=256)),
                ('imgUrl', models.CharField(max_length=256)),
                ('orderNum', models.CharField(max_length=256)),
                ('updateTime', models.DateTimeField()),
            ],
            options={
                'ordering': ['orderNum'],
            },
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='\u5bf9\u5e94\u7684\u5546\u54c1'),
        ),
    ]
